"""empty message

Revision ID: 53d70f80ee6d
Revises: a1b3aaad468b
Create Date: 2024-07-28 19:10:41.051554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53d70f80ee6d'
down_revision = 'a1b3aaad468b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Qc_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名可用于登录'),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('signatureText', sa.String(length=100), nullable=True),
    sa.Column('registerTime', sa.DateTime(), nullable=True),
    sa.Column('resetTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_Qc_Users_email'), 'Qc_Users', ['email'], unique=True)
    op.create_table('Qc_follows',
    sa.Column('followerId', sa.Integer(), nullable=False),
    sa.Column('followedId', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followedId'], ['Qc_Users.id'], ),
    sa.ForeignKeyConstraint(['followerId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('followerId', 'followedId')
    )
    op.create_table('Qc_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logTime', sa.DateTime(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('Qc_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('lastmodifytime', sa.DateTime(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_Qc_posts_status'), 'Qc_posts', ['status'], unique=False)
    op.create_table('Qc_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_postscollection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_poststars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('qc_follows')
    op.drop_table('qc_postscollection')
    op.drop_table('qc_logs')
    op.drop_index('ix_Qc_Users_email', table_name='qc_users')
    op.drop_index('username', table_name='qc_users')
    op.drop_table('qc_users')
    op.drop_table('qc_comment')
    op.drop_table('qc_poststars')
    op.drop_index('ix_Qc_posts_status', table_name='qc_posts')
    op.drop_table('qc_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('context', mysql.TEXT(), nullable=False),
    sa.Column('cover', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lastmodifytime', mysql.DATETIME(), nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_Qc_posts_status', 'qc_posts', ['status'], unique=False)
    op.create_table('qc_poststars',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('postsid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('qc_comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('parentid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('context', mysql.TEXT(), nullable=True),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('postsid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('qc_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True, comment='用户名可用于登录'),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('permission', mysql.JSON(), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('avatar', sa.BLOB(), nullable=True),
    sa.Column('signatureText', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('registerTime', mysql.DATETIME(), nullable=True),
    sa.Column('resetTime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('username', 'qc_users', ['username'], unique=True)
    op.create_index('ix_Qc_Users_email', 'qc_users', ['email'], unique=True)
    op.create_table('qc_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('logTime', mysql.DATETIME(), nullable=True),
    sa.Column('context', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否已读'),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('qc_postscollection',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('postsid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('qc_follows',
    sa.Column('followerId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('followedId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('followerId', 'followedId'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('Qc_poststars')
    op.drop_table('Qc_postscollection')
    op.drop_table('Qc_comment')
    op.drop_index(op.f('ix_Qc_posts_status'), table_name='Qc_posts')
    op.drop_table('Qc_posts')
    op.drop_table('Qc_logs')
    op.drop_table('Qc_follows')
    op.drop_index(op.f('ix_Qc_Users_email'), table_name='Qc_Users')
    op.drop_table('Qc_Users')
    # ### end Alembic commands ###
