"""empty message

Revision ID: f19f4242a224
Revises: 
Create Date: 2024-08-18 19:59:35.139303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19f4242a224'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Qc_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('signatureText', sa.String(length=100), nullable=True),
    sa.Column('registerTime', sa.DateTime(), nullable=True),
    sa.Column('resetTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_Qc_Users_email'), 'Qc_Users', ['email'], unique=True)
    op.create_table('Qc_Include',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listname', sa.String(length=300), nullable=False),
    sa.Column('context', sa.String(length=500), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('Qc_Labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labelname', sa.String(length=50), nullable=False),
    sa.Column('labeltext', sa.String(length=200), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('Qc_follows',
    sa.Column('followerId', sa.Integer(), nullable=False),
    sa.Column('followedId', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followedId'], ['Qc_Users.id'], ),
    sa.ForeignKeyConstraint(['followerId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('followerId', 'followedId')
    )
    op.create_table('Qc_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logTime', sa.DateTime(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('Qc_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('lastmodifytime', sa.DateTime(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_Qc_posts_status'), 'Qc_posts', ['status'], unique=False)
    op.create_table('Qc_PostsLabels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.Column('labelid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labelid'], ['Qc_Labels.id'], ),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_postscollection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_poststars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postsid'], ['Qc_posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Qc_poststars')
    op.drop_table('Qc_postscollection')
    op.drop_table('Qc_comment')
    op.drop_table('Qc_PostsLabels')
    op.drop_index(op.f('ix_Qc_posts_status'), table_name='Qc_posts')
    op.drop_table('Qc_posts')
    op.drop_table('Qc_logs')
    op.drop_table('Qc_follows')
    op.drop_table('Qc_Labels')
    op.drop_table('Qc_Include')
    op.drop_index(op.f('ix_Qc_Users_email'), table_name='Qc_Users')
    op.drop_table('Qc_Users')
    # ### end Alembic commands ###
